### ISSUE TITLE
Multiplayer commands give an error

### ISSUE THREAD

**Issue by Chik3r** [software-inc-multiplayer/software-inc-multiplayer#14] opened 2020-08-12 14:48 UTC
**Describe the bug**
When running `MULTIPLAYER_START` or `MULTIPLAYER_CONNECT` I get the following error: `Object reference not set to an instance of an object`

**To Reproduce**
1. Enable mod
2. Open console
3. Enter `MULTIPLAYER_START` or `MULTIPLAYER_CONNECT`

**Expected behaviour**
There should be no error

**Screenshots**
![alt text](https://i.imgur.com/J58mLLy.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Inc Version: Alpha 11.6.11
 - Mod Version: v0.2.1-unstable

**Comment by daredloco** [comment] 2020-08-12 15:23
This is "normal" behaviour, I'll upload a fix for this now.
The problem is that the commands should only be fired within the MainScene (Where the game happens) and not inside the menu or such because it does access the ingame companies and they only exist inside the MainScene.

I did create a fix for this and it will be included in version 0.2.2-unstable (it's already inside the nightly)

**Closed as completed by daredloco** 2020-08-12 15:23 UTC
Labels: Bug
